In [1]:
# Transpose of a matrix
import numpy as np

matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
print("Matrix:\n")
print(matrix)

print("\nTranspose of Matrix using nested list comprehension:\n")
transpose = [[matrix[j][i] for j in range(len(matrix))] for i in range(len(matrix[0]))]
for row in transpose:
    print(row)

print("\nTranspose of Matrix using numpy:\n")
print(np.transpose(matrix))

Matrix:

[[1 2 3]
 [4 5 6]
 [7 8 9]]

Transpose of Matrix using nested list comprehension:

[1, 4, 7]
[2, 5, 8]
[3, 6, 9]

Transpose of Matrix using numpy:

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [2]:
# Remove empty tuples from a list
def removetuple(num):
    num = filter(None, num)
    return num

num = [(), (1, 2), (3, 4), (), (5, 6), ()]
print("List:")
print(list(num))
print("Filtered list in reverse:")
num.reverse()
print(list(removetuple(num)))

List:
[(), (1, 2), (3, 4), (), (5, 6), ()]
Filtered list in reverse:
[(5, 6), (3, 4), (1, 2)]
